# Generated by Django 4.1.3 on 2022-11-08 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_employeedetails_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeDetails',
            new_name='EmployeeDetail',
        ),
    ]
