# Generated by Django 4.1.3 on 2022-11-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_employeedetails_employeedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='username',
        ),
    ]
