# Generated by Django 4.1.3 on 2022-11-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_issuedresource_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedresource',
            name='returned_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
