# Generated by Django 4.1.3 on 2022-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_issuedresource_returned_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedresource',
            name='returned_on',
        ),
        migrations.AddField(
            model_name='issuedresource',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
